#' @include makeLearners.R

# the monotonous learners
#' @importFrom regressoR.functional.models FunctionalModel.monotonous
.monotonous <- FunctionalModel.makeLearners(models = FunctionalModel.monotonous(),
                                            fitter = FunctionalModel.fit);
# the default learners
#' @importFrom regressoR.functional.models FunctionalModel.default
.default    <- FunctionalModel.makeLearners(models = FunctionalModel.default(),
                                            fitter = FunctionalModel.fit);

#' @title Get the Default Learners
#' @description Get the default learners for the models generated by
#'   \code{\link[regressoR.functional.models]{FunctionalModel.default}} for use
#'   in \code{\link[regressoR.base]{regressoR.applyLearners}}.
#' @return a list of default learners that can be applied in
#'   \code{\link[regressoR.base]{regressoR.applyLearners}}.
#' @export FunctionalModel.defaultLearners
#' @seealso FunctionalModel.makeLearners
FunctionalModel.defaultLearners <- function() {
  return(.default);
}

#' @title Get the Default Learners for Monotonously Decreasing Models
#' @description Get the default learners for the models generated by
#'   \code{\link[regressoR.functional.models]{FunctionalModel.monotonous}} for
#'   use in \code{\link[regressoR.base]{regressoR.applyLearners}}.
#' @return a list of default learners for models representing monotonously
#'   decreasing functions that can be applied in
#'   \code{\link[regressoR.base]{regressoR.applyLearners}}.
#' @export FunctionalModel.monotonousLearners
#' @seealso FunctionalModel.makeLearners
FunctionalModel.monotonousLearners <- function() {
  return(.default);
}
